### ISSUE TITLE
CORS blocked by browser. API doesn't return CORS related headers.

### ISSUE THREAD

**Issue by RanjanSushant** [AlexFlipnote/CoffeeAPI#4]

**Comment by fredsvanelli** [comment]
![image](https://user-images.githubusercontent.com/10292175/160462309-68a773cb-7fa0-40e2-89de-c3665be29cb9.png)

Same here. Can't GET the API with `Axios` locally

**Comment by AlexFlipnote** [comment]
Allow your localhost to access origins outside

**Comment by joaoestudante** [comment]
How would one go about doing that @AlexFlipnote?

**Comment by AlexFlipnote** [comment]
https://medium.com/swlh/avoiding-cors-errors-on-localhost-in-2020-5a656ed8cefa
